### ISSUE TITLE
A túróscsusza nagyon finom étel

### ISSUE THREAD

**Issue by szepeviktor** [turoscsusza/szalonna#8]
Mi lesz a honlap tartalma?

![Fúziós túrós csusza](http://rantotthuswokban.bmintbalazs.com/wp-content/uploads/Fuzios_turoscsusza-4.jpg)

**Comment by aronw8** [comment]
:)) semmi csak tesztelem a githubot, a cegunk at akar allni gitlabrol es
jirarol.

Te figyelsz engem?:)

**Comment by szepeviktor** [comment]
Igen, alulról a 3. vagy:
https://github.com/szepeviktor?tab=following

**Comment by szepeviktor** [comment]
@aronw8 Az Atlassian termékek nálam feketelistán vannak.

A GitLab meg sokkal rosszabb volt, de már nagyon másolják, és meg-meg haladják a GitHub-ot.

Csak az a poén, hogy a GitHub-nak nagyon harmonikus és használható a felülete - ezt még nem volt pénzük lemásolni!
